[package]
authors = ["smudge <nathan@ngriffith.com>"]
description = "A CLI for repairing timestamp metadata of file copies ğŸ•›ğŸ•§ğŸ•ğŸ•œğŸ•‘ğŸ•ğŸ•’"
edition = "2018"
license = "MIT OR Apache-2.0"
name = "timetime"
readme = "README.md"
repository = "https://github.com/smudge/timetime"
version = "0.1.0"

[dependencies]
getopts = "0.2"
ring = "0.17"
filetime = "0.2"
data-encoding = "2.3"

[dev-dependencies]
tempfile = "3"
